2021-04-21 01:08:55,184 [DEBUG] py4...: HTTP POST(http://127.0.0.1:1234/v1/commands/filetransfer/setSandbox), json: {'sandboxName': 'Yihang', 'copySamples': True, 'reinitialize': True}
2021-04-21 01:08:55,376 [DEBUG] py4...: OK[200], content: {
 "data": {"sandboxPath":"/Users/yxin/CytoscapeConfiguration/filetransfer/Yihang"},
 "errors":[]
}
2021-04-23 01:40:40,100 [DEBUG] py4...: Calling export_image('tx.png')
2021-04-23 01:40:40,101 [DEBUG] py4...: ǀCalling get_network_view_suid(None, base_url='http://127.0.0.1:1234/v1')
2021-04-23 01:40:40,101 [DEBUG] py4...: ǀǀCalling get_network_views(None, base_url='http://127.0.0.1:1234/v1')
2021-04-23 01:40:40,101 [DEBUG] py4...: ǀǀǀCalling get_network_suid(None, base_url='http://127.0.0.1:1234/v1')
2021-04-23 01:40:40,102 [DEBUG] py4...: ǀǀǀǀCalling commands_post('network get attribute network="current" namespace="default" columnList="SUID"', base_url='http://127.0.0.1:1234/v1')
2021-04-23 01:40:40,103 [DEBUG] py4...: ǀǀǀǀHTTP POST(http://127.0.0.1:1234/v1/commands/network/get%20attribute), json: {'network': 'current', 'namespace': 'default', 'columnList': 'SUID'}
2021-04-23 01:40:40,143 [DEBUG] py4...: ǀǀǀǀOK[200], content: {
 "data": [ {
  "SUID": 2895
}
],
 "errors":[]
}
2021-04-23 01:40:40,144 [DEBUG] py4...: ǀǀǀǀReturning 'commands_post': [{'SUID': 2895}]
2021-04-23 01:40:40,144 [DEBUG] py4...: ǀǀǀReturning 'get_network_suid': 2895
2021-04-23 01:40:40,144 [DEBUG] py4...: ǀǀǀCalling cyrest_get('networks/2895/views', base_url='http://127.0.0.1:1234/v1')
2021-04-23 01:40:40,144 [DEBUG] py4...: ǀǀǀHTTP GET(http://127.0.0.1:1234/v1/networks/2895/views)
2021-04-23 01:40:40,152 [DEBUG] py4...: ǀǀǀOK[200], content: [3611]
2021-04-23 01:40:40,152 [DEBUG] py4...: ǀǀǀReturning 'cyrest_get': [3611]
2021-04-23 01:40:40,152 [DEBUG] py4...: ǀǀReturning 'get_network_views': [3611]
2021-04-23 01:40:40,152 [DEBUG] py4...: ǀReturning 'get_network_view_suid': 3611
2021-04-23 01:40:40,152 [DEBUG] py4...: ǀCalling sandbox_get_file_info('tx.png')
2021-04-23 01:40:40,152 [DEBUG] py4...: ǀǀCalling commands_post('filetransfer getFileInfo fileName="/Users/yxin/git/cytoscape/RCy3/tx.png"', base_url='http://127.0.0.1:1234/v1')
2021-04-23 01:40:40,153 [DEBUG] py4...: ǀǀHTTP POST(http://127.0.0.1:1234/v1/commands/filetransfer/getFileInfo), json: {'fileName': '/Users/yxin/git/cytoscape/RCy3/tx.png'}
2021-04-23 01:40:40,159 [DEBUG] py4...: ǀǀOK[200], content: {
 "data": {"filePath":"/Users/yxin/git/cytoscape/RCy3/tx.png","modifiedTime":"","isFile":false},
 "errors":[]
}
2021-04-23 01:40:40,159 [DEBUG] py4...: ǀǀReturning 'commands_post': {'filePath': '/Users/yxin/git/cytoscape/RCy3/tx.png', 'modifiedTime': '', 'isFile': False}
2021-04-23 01:40:40,159 [DEBUG] py4...: ǀReturning 'sandbox_get_file_info': {'filePath': '/Users/yxin/git/cytoscape/RCy3/tx.png', 'modifiedTime': '', 'isFile': False}
2021-04-23 01:40:40,159 [DEBUG] py4...: ǀCalling commands_post('view export OutputFile="/Users/yxin/git/cytoscape/RCy3/tx.png" options="PNG" view="SUID:3611"', base_url='http://127.0.0.1:1234/v1')
2021-04-23 01:40:40,159 [DEBUG] py4...: ǀHTTP POST(http://127.0.0.1:1234/v1/commands/view/export), json: {'OutputFile': '/Users/yxin/git/cytoscape/RCy3/tx.png', 'options': 'PNG', 'view': 'SUID:3611'}
2021-04-23 01:40:40,207 [DEBUG] py4...: ǀOK[200], content: {
 "data": {"file":"/Users/yxin/git/cytoscape/RCy3/tx.png"},
 "errors":[]
}
2021-04-23 01:40:40,207 [DEBUG] py4...: ǀReturning 'commands_post': {'file': '/Users/yxin/git/cytoscape/RCy3/tx.png'}
2021-04-23 01:40:40,207 [DEBUG] py4...: Returning 'export_image': {'file': '/Users/yxin/git/cytoscape/RCy3/tx.png'}
2021-04-23 01:40:40,207 [DEBUG] py4...: --------------------
2021-04-29 00:03:14,015 [DEBUG] py4...: Calling open_session('cytoscape.cys')
2021-04-29 00:03:14,017 [DEBUG] py4...: ǀCalling commands_post('session open file="/Users/yxin/git/cytoscape/RCy3/cytoscape.cys"', base_url='http://127.0.0.1:1234/v1')
2021-04-29 00:03:14,019 [DEBUG] py4...: ǀHTTP POST(http://127.0.0.1:1234/v1/commands/session/open), json: {'file': '/Users/yxin/git/cytoscape/RCy3/cytoscape.cys'}
2021-04-29 00:03:14,194 [DEBUG] py4...: ǀInternal Server Error[500], content: {
 "data": {},
 "errors":[{"status":500,"type":"urn:cytoscape:ci:cyrest-core:v1:handle-json-command:errors:2","message":"File \u0027cytoscape.cys\u0027 not found:","link":"file:/Users/yxin/CytoscapeConfiguration/3/framework-cytoscape.log"}]
}
2021-04-29 00:03:14,194 [DEBUG] py4...: ǀ'commands_post' exception CyError("In commands_post(): File 'cytoscape.cys' not found:")
2021-04-29 00:03:14,194 [DEBUG] py4...: 'open_session' exception CyError("In commands_post(): File 'cytoscape.cys' not found:")
2021-04-29 00:03:14,195 [DEBUG] py4...: --------------------
